### ISSUE TITLE
Unable to build PDF  due unexpected identifier

### ISSUE THREAD

**Issue by joordy** [signcl/docusaurus-prince-pdf#15]
Hi! After using your `docusaurus-prince-pdf` package for a while, I'd discovered a new problem. When creating a PDF using the following script: 

`npx docusaurus-prince-pdf -u https://docusaurus.io/docs`

I've ran in the following problem:

```bash
file:///Users/jordy/node_modules/docusaurus-prince-pdf/index.js:9
import pkg from './package.json' assert { type: 'json' };
                                 ^^^^^^

SyntaxError: Unexpected identifier
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
    at async link (internal/modules/esm/module_job.js:67:21)
```

Here is the [source code](https://github.com/joordy/documentation) to my documentation, which are generated using Docusaurus 2.0.0-beta.18. Could you please help me out? Thanks!

**Comment by sparanoid** [comment]
What Node.js version are you using? This syntax seems requires Node 16 or higher. You can try using it with Docker image.

**Comment by sparanoid** [comment]
Here's a working example for your site:

```bash
docker run --rm -it --init \
  -v $(pwd)/pdf:/app/pdf openbayes/docusaurus-prince-pdf \
  -u https://graduation-documentation.vercel.app/ \
  -s '.pagination-nav__item--next .pagination-nav__link' \
  --include-index
```

**Comment by joordy** [comment]
Hi! 

I'm currently using Node v16.14, but still getting the error message. Also with older stable versions I still get the same error. 

Also, the docker command won't work for me, I'm when running the following script:
```
docker run --rm -it --init \
  -v $(pwd)/pdf:/app/pdf openbayes/docusaurus-prince-pdf \
  -u https://graduation.jorrr.dev/ \
  -s '.pagination-nav__item--next .pagination-nav__link' \
  --include-index
```

And this is the result I'm getting
```Executing command: prince --no-warn-css --style=/app/print.css --input-list=./pdf/graduation.jorrr.dev.txt -o ./pdf/graduation.jorrr.dev.pdf 
Error: Command failed: prince --no-warn-css --style=/app/print.css --input-list=./pdf/graduation.jorrr.dev.txt -o ./pdf/graduation.jorrr.dev.pdf 
/usr/local/bin/prince: exec: line 3: /usr/local/lib/prince/bin/prince: not found

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'prince --no-warn-css --style=/app/print.css --input-list=./pdf/graduation.jorrr.dev.txt -o ./pdf/graduation.jorrr.dev.pdf '
}```


I even re-installed prince, without any succes..

**Comment by chungminhtu** [comment]
The problem happened because you don't install Prince first. You have to install it here: https://www.princexml.com/download/

**Comment by tomchon** [comment]
@sparanoid  hi ,i start to use  this tools on mac m4 . The same issue for me ：
```
➜  temp npx docusaurus-prince-pdf -u https://docusaurus.io/docs

file:///Users/apple/.npm/_npx/85d58867f08057bf/node_modules/docusaurus-prince-pdf/index.js:11
import pkg from './package.json' assert { type: 'json' };
                                 ^^^^^^

SyntaxError: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:338:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:102:18)
    at #translate (node:internal/modules/esm/loader:437:12)
    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:484:27)
    at async ModuleJob._link (node:internal/modules/esm/module_job:115:19)

Node.js v22.12.0
➜  temp prince --version
Prince 16.1
Copyright 2002-2025 YesLogic Pty. Ltd.
Non-commercial License

```

**Comment by tomchon** [comment]
it seems that Node.js v22 has changes in compatibility with assert { type: 'json' }, and some packages have not adapted to it yet. i use Node.js v20 and it works.
