### ISSUE TITLE
Extra pages

### ISSUE THREAD

**Issue by hatton** [signcl/docusaurus-prince-pdf#5]
Using

`npx docusaurus-prince-pdf -u https://docusaurus.io/docs/cli --selector '.pagination-nav__link--next'`

I get a PDF in which every other page is empty:

![image](https://user-images.githubusercontent.com/8448/168601949-cebd0f66-e8b8-45ac-bb64-9d1a777c2dd6.png)

I don't know if it matters, but I'm in the USA and the pages are coming out 8.5 x 11 in, not A4.

Any ideas?

**Comment by sparanoid** [comment]
@hatton What version are you using?

```
npx docusaurus-prince-pdf --version
```

I've just released v1.0.7. Let me see if it works for you.

**Comment by joseantgv** [comment]
I have the same problem.

And:
`npx docusaurus-prince-pdf --version` returns `unkown`

**Comment by joseantgv** [comment]
> 

A couple of issues:

`docker: Error response from daemon: create $(pwd)/pdf: "$(pwd)/pdf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.`

_I'm running on Windows_

So I tried:

`docker run --rm -it -v d:\temp openbayes/docusaurus-prince-pdf:master -u http://localhost:3000/docs/`

And the result:

`Error: RequestError: connect ECONNREFUSED 127.0.0.1:3000
    at ClientRequest.<anonymous> (file:///app/node_modules/got/dist/source/core/index.js:754:107)`

I have "build && serve" my instance and it's accessible with the browser. Maybe it's not working in local environment?

Thanks for your effort :raised_hands:

**Comment by sparanoid** [comment]
> Error: RequestError: connect ECONNREFUSED 127.0.0.1:3000 at ClientRequest.<anonymous>

If you need to generate PDF from localhost using Docker image. You need to replace `localhost` with `host.docker.internal` to make sure it can be access from inside the container.

**Comment by joseantgv** [comment]
> > Error: RequestError: connect ECONNREFUSED 127.0.0.1:3000 at ClientRequest.
> 
> If you need to generate PDF from localhost using Docker image. You need to replace `localhost` with `host.docker.internal` to make sure it can be access from inside the container.

Oh same problem :(

`docker run --rm -it -v d:\temp openbayes/docusaurus-prince-pdf:master -u http://host.docker.internal:3000/docs/
Error: RequestError: getaddrinfo ENOTFOUND host.docker.internal
    at ClientRequest.<anonymous> (file:///app/node_modules/got/dist/source/core/index.js:754:107)`

**Comment by sparanoid** [comment]
@joseantgv [This](https://stackoverflow.com/a/24326540/412385) works for me on macOS :(

Try to deploy your site external so that program inside the container can access it. 

Or you can try the latest `npx` version and make sure the `--selector` option match your site.

**Comment by joseantgv** [comment]
> @joseantgv [This](https://stackoverflow.com/a/24326540/412385) works for me on macOS :(
> 
> Try to deploy your site external so that program inside the container can access it.
> 
> Or you can try the latest `npx` version and make sure the `--selector` option match your site.

Ok, we move forward :) I have uploaded the content to a public site and it's fetched now.

But I get:

`Executing command: prince --no-warn-css --style=/app/print.css --input-list=./pdf/XX.txt -o ./pdf/XX.pdf
Error: Command failed: prince --no-warn-css --style=/app/print.css --input-list=./pdf/XX.txt -o ./pdf/XX.pdf
/usr/local/bin/prince: exec: line 3: /usr/local/lib/prince/bin/prince: not found`

**Comment by yevgenymakarov** [comment]
These blank pages are caused by long code blocks, to fix see #31.
