### ISSUE TITLE
Error: HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by beniroquai** [signcl/docusaurus-prince-pdf#89]
Similar to #1 I also get this error on multiple different Docusaurus instances. I don't know what's the reason for this. Is there a specific setting I would need to perform in the configuration (certain link to the `/docs` folder?)

Error:
```bash
(base) Blynk:prince-15.4-macos bene$ npx docusaurus-prince-pdf -u http://openuc2.github.io/docs --trace-warnings
(node:85062) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///Users/bene/.npm/_npx/85d58867f08057bf/node_modules/docusaurus-prince-pdf/index.js:175
    throw new Error(err);
          ^

Error: HTTPError: Response code 404 (Not Found)
    at file:///Users/bene/.npm/_npx/85d58867f08057bf/node_modules/docusaurus-prince-pdf/index.js:175:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestPage (file:///Users/bene/.npm/_npx/85d58867f08057bf/node_modules/docusaurus-prince-pdf/index.js:136:3)

Node.js v20.12.0
```

The docusaurus page refers to https://openuc2.github.io/docs/intro, but even using this link in the docusaurus-prince-pdf doesn't resolve the issue. Same with a freshly generated local copy of docusuaurs 3.5 does not work. I think I'm missing something. Thanks!

**Comment by sparanoid** [comment]
The base URL (`-u`) you pass must be the first page of your docs which has consistent next pagination link.

In your example:

<img width="380" alt="image" src="https://github.com/user-attachments/assets/8c493278-6346-44d0-9776-70d4b826defb" />

You choose https://openuc2.github.io/docs/intro as the base URL but it is the last page of your docs. There is no "next" link on this page so 404 occurred.

You can either:

- Make the intro page the first page of your docs if you're the docs owner
- Pass the first page of the docs as base URL. Should be `https://openuc2.github.io/docs/General/ModuleDeveloperKit/` in this case
- Manually create the list file then generate the PDF with `--pdf-only` flag

**Comment by Brainpitcher** [comment]
the same for me with  https://docs.seven.tech/

`npx docusaurus-prince-pdf -u https://docs.seven.tech/ --output docs.pdf      `

gives:

```
PS C:\Users\Brainpitcher> npx docusaurus-prince-pdf -u https://docs.seven.tech/ --output docs.pdf           
(node:41032) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Got link: https://docs.seven.tech/docs/manual
Got link: https://docs.seven.tech/docs/smpp
Got link: https://docs.seven.tech/docs/api
No next link found!
Writing buffer (3 links) to ./pdf/docs.seven.tech.txt
Generating PDF docs.pdf
Executing command: prince --no-warn-css --style=/C:/Users/Brainpitcher/AppData/Local/npm-cache/_npx/85d58867f08057bf/node_modules/docusaurus-prince-pdf/print.css  --input-list=./pdf/docs.seven.tech.txt -o docs.pdf
file:///C:/Users/Brainpitcher/AppData/Local/npm-cache/_npx/85d58867f08057bf/node_modules/docusaurus-prince-pdf/index.js:131
    throw new Error(err);
          ^

Error: Error: Command failed: prince --no-warn-css --style=/C:/Users/Brainpitcher/AppData/Local/npm-cache/_npx/85d58867f08057bf/node_modules/docusaurus-prince-pdf/print.css  --input-list=./pdf/docs.seven.tech.txt -o docs.pdf
"prince" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

    at file:///C:/Users/Brainpitcher/AppData/Local/npm-cache/_npx/85d58867f08057bf/node_modules/docusaurus-prince-pdf/index.js:131:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generatePdf (file:///C:/Users/Brainpitcher/AppData/Local/npm-cache/_npx/85d58867f08057bf/node_modules/docusaurus-prince-pdf/index.js:127:3)

Node.js v18.0.0
```

**Comment by luandro** [comment]
I still have the same issue, has a fix been found?

**Comment by mdestafadilah** [comment]
> I still have the same issue, has a fix been found?

no until now...

**Comment by MasterYuan418** [comment]
> > I still have the same issue, has a fix been found?
> 
> no until now...

okay, so I tried to debug the code, find that if you change `index.js` line 125, from `prince --no-warn-css` to `<Path>\prince.exe --no-warn-css ...`, it works. But all the CSS styles are gone.

For example, if the prince installed in `C:\Programs\Prince`, you just change to `C:\Program\Prince\engine\bin\prince.exe`
